on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        registry-url: https://npm.pkg.github.com
    - run: npm init --scope ${{ github.repository_owner }} -y

    - run: npm publish
      continue-on-error: true
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete packages
      uses: ./.github/actions/delete-package-version
      with:
        name: package-count
        version: 1.0.0
