on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1
      with:
        registry-url: https://npm.pkg.github.com
    - run: npm init --scope ${{ github.repository_owner }} -y

    - run: npm publish
      continue-on-error: true
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete packages
      run: |
        dotnet tool install gpr -g
        gpr delete ${{ github.repository }} --force -k ${{ secrets.GITHUB_TOKEN }}
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
